package com.mileticgo.app.utils

enum class LocationCategory(val title: String) {
    CENTAR("CENTAR") ,
    KEJ("KEJ"),
    LIMAN("LIMAN"),
    PODBARA("PODBARA"),
    GRBAVICA("GRBAVICA"),
    PETROVARADIN("PETROVARADIN"),
    ROTKVARIJA("ROTKVARIJA"),
    SAJMISTE("SAJMIŠTE"),
    SALAJKA("SALAJKA"),
    TELEP("TELEP"),
    MISELUK("MIŠELUK"),
    VIDOVDANSKO_NASELJE("VIDOVDANSKO NASELJE"),
    AVIJATICARSKO_NASELJE("AVIJATIČARSKO NASELJE"),
    SREMSKA_KAMENICA("SREMSKA KAMENICA"),
    SLANA_BARA("SLANA BARA"),
    STARI_GRAD("STARI GRAD")
}